services:
  ais:
    container_name: web
    build:
      context: "."
    ports:
      - 8080:8080
    depends_on:
      - db
    network_mode: host

  db:
    container_name: postgres
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    network_mode: host

volumes:
  pgdata:
